server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/pavanreddy-1724/mini-ecommerce-microservices.git
          clone-on-start: true
          default-label: main
          search-paths: configs
          # 👆 tells Config Server to look inside the 'configs' folder in your repo

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
